# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Sale.delete_all()
Bike.delete_all()
Customer.delete_all()

bike1 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Specialized', 'model' => 'Allez', 'colour' => 'Red/black', 'size' => 'L', 'price' => 750.00})
bike1.save()
bike2 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Specialized', 'model' => 'Allez', 'colour' => 'Red/black', 'size' => 'L', 'price' => 750.00})
bike2.save()
bike3 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Specialized', 'model' => 'Allez', 'colour' => 'Red/white', 'size' => 'M', 'price' => 750.00})
bike3.save()
bike4 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'White/red', 'size' => 'L', 'price' => 650.00})
bike4.save()
bike5 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'White/red', 'size' => 'L', 'price' => 650.00})
bike5.save()
bike6 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'Blue/black', 'size' => 'M', 'price' => 650.00})
bike6.save()
bike7 = Bike.new({'category' => 'Mens', 'bike_type' => 'Road', 'brand_name' => 'Pinarello', 'model' => 'Dogma', 'colour' => 'Red/blue', 'size' => 'L', 'price' => 8000.00})
bike7.save()
bike8= Bike.new({'category' => 'Mens','bike_type' => 'Road', 'brand_name' => 'Ridley', 'model' => 'Fenix', 'colour' => 'Red/black', 'size' => 'L', 'price' => 2500.00})
bike8.save()
bike9 = Bike.new({'category' => 'Mens','bike_type' => 'Road', 'brand_name' => 'Ridley', 'model' => 'Fenix', 'colour' => 'Red/white', 'size' => 'L', 'price' => 2500.00})
bike9.save()
bike10 = Bike.new({'category' => 'Mens','bike_type' => 'Hybrid', 'brand_name' => 'Specialized', 'model' => 'Crosstrail', 'colour' => 'Black/red', 'size' => 'L', 'price' => 500.00})
bike10.save()
bike11 = Bike.new({'category' => 'Mens','bike_type' => 'Hybrid', 'brand_name' => 'Specialized', 'model' => 'Crosstrail', 'colour' => 'Red/black', 'size' => 'L', 'price' => 750.00})
bike11.save()
bike12 = Bike.new({'category' => 'Mens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'L', 'price' => 500.00})
bike12.save()
bike13 = Bike.new({'category' => 'Mens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'L', 'price' => 500.00})
bike13.save()
bike14 = Bike.new({'category' => 'Mens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'M', 'price' => 500.00})
bike14.save()
bike15 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Specialized', 'model' => 'Rockhopper', 'colour' => 'Red/black', 'size' => 'L', 'price' => 750.00})
bike15.save()
bike16 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Specialized', 'model' => 'Stumpjumper', 'colour' => 'Red/black', 'size' => 'L', 'price' => 2600.00})
bike16.save()
bike17 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Specialized', 'model' => 'Rockhopper', 'colour' => 'Red/white', 'size' => 'M', 'price' => 750.00})
bike17.save()
bike18 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Santa Cruz', 'model' => 'V10', 'colour' => 'Orange', 'size' => 'M', 'price' => 7500.00})
bike18.save()
bike19 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/white', 'size' => 'L', 'price' => 400.00})
bike19.save()
bike20 = Bike.new({'category' => 'Mens', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/black', 'size' => 'M', 'price' => 400.00})
bike20.save()
bike21 = Bike.new({'category' => 'Womens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'White/red', 'size' => 'L', 'price' => 650.00})
bike21.save()
bike22 = Bike.new({'category' => 'Womens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'White/red', 'size' => 'M', 'price' => 650.00})
bike22.save()
bike23 = Bike.new({'category' => 'Womens', 'bike_type' => 'Road', 'brand_name' => 'Giant', 'model' => 'Defy', 'colour' => 'Blue/black', 'size' => 'M', 'price' => 650.00})
bike23.save()
bike24 = Bike.new({'category' => 'Womens', 'bike_type' => 'Road', 'brand_name' => 'Specialized', 'model' => 'Allez', 'colour' => 'Red/blue', 'size' => 'M', 'price' => 600.00})
bike24.save()
bike25= Bike.new({'category' => 'Womens','bike_type' => 'Road', 'brand_name' => 'Ridley', 'model' => 'Fenix', 'colour' => 'Red/black', 'size' => 'L', 'price' => 2500.00})
bike25.save()
bike26 = Bike.new({'category' => 'Womens','bike_type' => 'Road', 'brand_name' => 'Ridley', 'model' => 'Fenix', 'colour' => 'Red/white', 'size' => 'M', 'price' => 2500.00})
bike26.save()
bike27 = Bike.new({'category' => 'Womens','bike_type' => 'Hybrid', 'brand_name' => 'Specialized', 'model' => 'Crosstrail', 'colour' => 'Black/red', 'size' => 'M', 'price' => 500.00})
bike27.save()
bike28 = Bike.new({'category' => 'Womens','bike_type' => 'Hybrid', 'brand_name' => 'Specialized', 'model' => 'Crosstrail', 'colour' => 'Red/black', 'size' => 'L', 'price' => 750.00})
bike28.save()
bike29 = Bike.new({'category' => 'Womens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'L', 'price' => 500.00})
bike29.save()
bike30 = Bike.new({'category' => 'Womens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'L', 'price' => 500.00})
bike30.save()
bike31 = Bike.new({'category' => 'Womens','bike_type' => 'Hybrid', 'brand_name' => 'Whyte', 'model' => 'Whitechapel', 'colour' => 'Grey', 'size' => 'M', 'price' => 500.00})
bike31.save()
bike32 = Bike.new({'category' => 'Womens', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/white', 'size' => 'L', 'price' => 400.00})
bike32.save()
bike33 = Bike.new({'category' => 'Womens', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/black', 'size' => 'M', 'price' => 400.00})
bike33.save()
bike34 = Bike.new({'category' => 'Kids', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/white', 'size' => 'M', 'price' => 200.00})
bike34.save()
bike35 = Bike.new({'category' => 'Kids', 'bike_type' => 'Mountain', 'brand_name' => 'Ghost', 'model' => 'Kato', 'colour' => 'Red/black', 'size' => 'M', 'price' => 200.00})
bike35.save()
bike36 = Bike.new({'category' => 'Kids', 'bike_type' => 'Starter', 'brand_name' => 'Isla', 'model' => 'Cnoc', 'colour' => 'Green', 'size' => 'M', 'price' => 250.00})
bike36.save()
bike37 = Bike.new({'category' => 'Kids', 'bike_type' => 'Starter', 'brand_name' => 'Isla', 'model' => 'Cnoc', 'colour' => 'Green', 'size' => 'S', 'price' => 250.00})
bike37.save()
bike38 = Bike.new({'category' => 'Womens', 'bike_type' => 'BMX', 'brand_name' => 'Stolen', 'model' => 'Casino', 'colour' => 'Black', 'size' => 'M', 'price' => 200.00})
bike38.save()
bike39 = Bike.new({'category' => 'Kids', 'bike_type' => 'BMX', 'brand_name' => 'Stolen', 'model' => 'Casino', 'colour' => 'Black', 'size' => 'S', 'price' => 125.00})
bike39.save()
bike40 = Bike.new({'category' => 'Mens', 'bike_type' => 'BMX', 'brand_name' => 'Stolen', 'model' => 'Casino', 'colour' => 'Black', 'size' => 'L', 'price' => 250.00})
bike40.save()


customer1 = Customer.new({ 'name' => 'David O Leary', 'address' => '77, The Murrays Brae EH17 8UJ', 'phone' => '12345678912'})
customer1.save()
customer2 = Customer.new({ 'name' => 'Tara O Leary', 'address' => '78, The Murrays Brae EH17 8UK', 'phone' => '12345678913'})
customer2.save()
customer3 = Customer.new({ 'name' => 'Conor O Leary', 'address' => '79, The Murrays Brae EH17 8UL', 'phone' => '12345678914'})
customer3.save()
customer4 = Customer.new({ 'name' => 'Liam O Leary', 'address' => '80, The Murrays Brae EH17 8UM', 'phone' => '12345678915'})
customer4.save()
customer5 = Customer.new({ 'name' => 'Ric McLaughlin', 'address' => '81, The Murrays Brae EH17 8UN', 'phone' => '12345678916'})
customer5.save()


sale1 = Sale.new({'bike_id' => bike1.id, 'customer_id' => customer1.id})
sale1.save()
sale2 = Sale.new({'bike_id' => bike2.id, 'customer_id' => customer1.id})
sale2.save()
sale3 = Sale.new({'bike_id' => bike3.id, 'customer_id' => customer2.id})
sale3.save()
sale4 = Sale.new({'bike_id' => bike4.id, 'customer_id' => customer1.id})
sale4.save()
sale5 = Sale.new({'bike_id' => bike5.id, 'customer_id' => customer2.id})
sale5.save()
sale6 = Sale.new({'bike_id' => bike3.id, 'customer_id' => customer5.id})
sale6.save()
sale7 = Sale.new({'bike_id' => bike20.id, 'customer_id' => customer4.id})
sale7.save()
sale8 = Sale.new({'bike_id' => bike34.id, 'customer_id' => customer3.id})
sale8.save()